### ISSUE TITLE
NS prefix is iOS style

### ISSUE THREAD

**Issue by kazuman519** [mattak/KotlinMoment#15]
https://github.com/mattak/KotlinMoment/blob/master/src/main/kotlin/me/mattak/moment/Duration.kt#L119

**Comment by mattak** [comment]
OK. I think NS dateformat conversion is useless and not needed any more.
So I decided to remove the function.

**Comment by mattak** [comment]
Anyway thanks for reporting! @kazuman519 

The function is removed.
- https://github.com/mattak/KotlinMoment/pull/16
