### ISSUE TITLE
doesn't wok on not JST time zone

### ISSUE THREAD

**Issue by mihyaeru21** [mattak/KotlinMoment#2]

**Comment by mattak** [comment]
You can do it :+1:

**Comment by pine** [comment]
:+1:

**Comment by kazuman519** [comment]
👍

**Comment by mattak** [comment]
May be SimpleDateFormate returns UTC Date object.
Date object doesnot hold any of offset data.
So when you format it, the hour is different.

I'm thinking the solution, may be next release 0.0.2 would be solve it.

**Comment by mattak** [comment]
Date time parser should include locale time.

**Comment by pine** [comment]
:+1:

**Comment by pine** [comment]
:+1:

**Comment by akihiro0228** [comment]
:+1:

**Comment by mihyaeru21** [comment]
:sunglasses::+1:

**Comment by kazuman519** [comment]
🍖

**Comment by pine** [comment]
:+1:

**Comment by mattak** [comment]
YEAAAAH. ok. I'll fix it in few days.

**Comment by pine** [comment]
👍

**Comment by mattak** [comment]
OK! I'll check it!

**Comment by mattak** [comment]
@pine

It seems every SimpleDateFormat referring timezone and locale.

-
 https://github.com/mattak/KotlinMoment/blob/master/src/main/kotlin/me/mattak/moment/MomentExtensions.kt#L27-L28
- https://github.com/mattak/KotlinMoment/blob/master/src/main/kotlin/me/mattak/moment/Moment.kt#L192-L193

Do you remember what was the problem?
If you do not remind it, I'll close this issue.

**Comment by pine** [comment]
@mattak Sorry, I not remember problems 😔

**Comment by mattak** [comment]
@pine Thanks! I closed!
